#!/bin/sh

exec_single() {
  prog=$1
  shift
  (ps -A | grep $prog) || $prog $@ &
}

# monitor config
~/localscripts/monitor-adjust
feh --bg-scale "/home/sherwyn/Pictures/forest.jpg"

# startup apps
exec_single udiskie --tray
exec_single connman-gtk
exec_single flameshot
exec_single fcitx5
exec_single pulseaudio -D
exec_single pasystray

# keyboard mods
setxkbmap -option caps:ctrl_modifier

